### ISSUE TITLE
Possibility to add colored frames to tiles

### ISSUE THREAD

**Issue by joti** [Koki-Yamaguchi/carcassonne-simulator#2]
We're using this great tool to create illustrations to our Carcassonne strategy guide. We would like to indicate which are the latest tiles of the players by coloring the frames of those tiles (see attached image). Could you please add a feature like this?
![tamadas2](https://user-images.githubusercontent.com/10690151/221383808-34da7024-28cd-4377-b5ce-129e99444a50.jpg)

**Comment by Koki-Yamaguchi** [comment]
Hello, thank you for using my tool and suggesting a new feature.

I didn't really want to add a lot of features for its simplicity, but this feature seems crucially important to me as well, so l'll try to add it soon.

@joti

**Comment by Koki-Yamaguchi** [comment]
Added the feature!

@joti

**Comment by joti** [comment]
Thanks for the quick response. May I ask for a minor change? Could the frame itself be a tiny bit larger? Now the edges of the tiles are visible beyond the frame.
![frame](https://user-images.githubusercontent.com/10690151/223662757-4ee71fbd-8870-441f-abc4-26f7e4013444.JPG)

**Comment by Koki-Yamaguchi** [comment]
Thank you for the feedback.

This is actually a minor bug probably depending on your environment (which didn't reproduce on my environment). Hence, I can't fix this by just enlarging the border line, because it breaks the design in my browser.

Could you tell me about the browser you're using, so that I can reproduce that?

Sorry for the inconvenience.

(below is what I see in my browser (Chrome on Android or Mac))
![Screenshot_20230308_214322_com android chrome](https://user-images.githubusercontent.com/22830759/223716646-e2637ca2-ce0e-4b88-9ed6-a30c4ae76536.jpg)

**Comment by joti** [comment]
You're right, the bug is only present when I'm using Firefox. In Chrome everything's fine.

**Comment by Koki-Yamaguchi** [comment]
Thank you again for reporting the bug. I fixed it.

@joti
